// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMyAccount.Models;

namespace WebMyAccount.Migrations
{
    [DbContext(typeof(MyAccountContext))]
    [Migration("20190126130957_MySecondMigration")]
    partial class MySecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("WebMyAccount.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Ratio");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WebMyAccount.Models.Record", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Info");

                    b.Property<DateTime>("RecordDate");

                    b.HasKey("RecordId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("WebMyAccount.Models.RecordDetail", b =>
                {
                    b.Property<long>("RecordDetailId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountId");

                    b.Property<decimal>("Asset");

                    b.Property<decimal>("Debt");

                    b.Property<string>("Info");

                    b.Property<long>("RecordId");

                    b.HasKey("RecordDetailId");

                    b.HasIndex("AccountId");

                    b.ToTable("RecordDetails");
                });

            modelBuilder.Entity("WebMyAccount.Models.RecordDetail", b =>
                {
                    b.HasOne("WebMyAccount.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
